name: Terraform Apply

on:
  workflow_dispatch:

env:
    GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
    GIT_BRANCH: ${GITHUB_REF#refs/heads/}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Execute terraform plan
        run: echo Here you will apply terraform changes

