name: Terraform plan

on:
  workflow_dispatch:

env:
    GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    if: contains('["staging","main"]', github.ref_name)

    steps:
      - uses: actions/checkout@v4

      - name: Execute terraform plan
        run: echo Here you should be able to see what changes will apply.

